name: Build, Push, and Deploy Backend

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/skillback-docker .
        docker push ${{ secrets.DOCKER_USERNAME }}/skillback-docker

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and Deploy Backend
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/skillback-docker
          docker stop skillback-docker || true
          docker rm skillback-docker || true
          docker run -d -p 4000:10000 --name skillback-docker ${{ secrets.DOCKER_USERNAME }}/skillback-docker